POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "name": "brod test",
    "email": "chad1email.com",
    "password": "chad111"
}

###

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "chad1@email.com",
    "password": "chad111"
}

###
GET http://localhost:3000/api/posts
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTU4NjZkM2RkZDY2MDkyNzVmNTIyZjIiLCJpYXQiOjE2MzMxODY5ODUsImV4cCI6MTYzMzE4NzAxNX0.ZYYgvjIU7n5YkunKXz8MkFl8dm24NnaPx6EqxhMbUQo


###
GET http://localhost:3000/api/habits/show
auth-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTU4NjZkM2RkZDY2MDkyNzVmNTIyZjIiLCJpYXQiOjE2MzMzMzU5OTEsImV4cCI6MTYzMzMzOTU5MX0.CB3cBk6Sm2Ivo3y571i6wNfqov7-0OB09I34q46ff-Q

###
POST http://localhost:3000/api/habits/add
auth-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTU4NjZkM2RkZDY2MDkyNzVmNTIyZjIiLCJpYXQiOjE2MzMyNjE5MzQsImV4cCI6MTYzMzI2NTUzNH0.SH6XbrGFrVyIJbvwOvA9NmOwJXChiTvuCHBGU9RT5Fo
Content-Type: application/json

{
    "name": "testing-from-post-req",
    
}

###
DELETE http://localhost:3000/api/habits/remove/test-habit
auth-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTU4NjZkM2RkZDY2MDkyNzVmNTIyZjIiLCJpYXQiOjE2MzMyNTkwMTIsImV4cCI6MTYzMzI2MjYxMn0.mL91Fm-h16Tjsk5Avgt2uKTrzMgjJqkfzMG7iX-1V5g

###
PATCH http://localhost:3000/api/habits/update/current/0
auth-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTU4NjZkM2RkZDY2MDkyNzVmNTIyZjIiLCJpYXQiOjE2MzMzMzU5OTEsImV4cCI6MTYzMzMzOTU5MX0.CB3cBk6Sm2Ivo3y571i6wNfqov7-0OB09I34q46ff-Q